#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Figure X: MSM-based mouth–cover gating for CypX.

Panel A: stacked bar chart of macrostate populations (open / intermediate / closed)
Panel B: bar chart of MFPT (closed -> open, frames)

This version reads new results from:
  msm_mouth_cover_summary.dat
generated by msm_mouth_cover_all.py

Color scheme:
  Panel A (macrostates): Open=blue, Intermediate=orange, Closed=green
  Panel B (systems): APO=black, PIY=red, AND=blue, EST=green, TES=purple
"""

import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

SUMMARY_FILE = Path("msm_mouth_cover_summary.dat")

def load_summary(path: Path):
    """
    Parse msm_mouth_cover_summary.dat
    Expected columns:
      sys  pop_open  pop_intermediate  pop_closed  MFPT_closed_to_open(frames)
    """
    systems = []
    pop_open = []
    pop_inter = []
    pop_closed = []
    mfpt_frames = []

    with path.open("r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if len(parts) < 5:
                continue
            systems.append(parts[0])
            pop_open.append(float(parts[1]))
            pop_inter.append(float(parts[2]))
            pop_closed.append(float(parts[3]))
            mfpt_frames.append(float(parts[4]))

    return (
        systems,
        np.array(pop_open, dtype=float),
        np.array(pop_inter, dtype=float),
        np.array(pop_closed, dtype=float),
        np.array(mfpt_frames, dtype=float),
    )

def main():
    if not SUMMARY_FILE.exists():
        raise FileNotFoundError(
            f"Cannot find {SUMMARY_FILE}. Run msm_mouth_cover_all.py first."
        )

    systems, pop_open, pop_inter, pop_closed, mfpt_frames = load_summary(SUMMARY_FILE)

    # ----------------- plotting -----------------
    plt.rcParams["font.size"] = 11
    fig, axes = plt.subplots(1, 2, figsize=(11, 4.5))

    # ===== Panel A: stacked populations =====
    ax = axes[0]
    x = np.arange(len(systems))

    # ---- Panel A colors (match your Fig.1): Open=blue, Intermediate=orange, Closed=green ----
    color_open = "#1f77b4"   # blue
    color_inter = "#ff7f0e"  # orange
    color_closed = "#2ca02c" # green

    ax.bar(x, pop_open, label="Open", color=color_open)
    ax.bar(x, pop_inter, bottom=pop_open, label="Intermediate", color=color_inter)
    ax.bar(x, pop_closed, bottom=pop_open + pop_inter, label="Closed", color=color_closed)

    ax.set_xticks(x)
    ax.set_xticklabels(systems)
    ax.set_ylim(0.0, 1.2)  # leave space for legend
    ax.set_ylabel("Equilibrium population")
    ax.set_title("MSM mouth–cover macrostates")

    ax.legend(
        loc="upper center",
        ncol=3,
        frameon=False
    )

    # ===== Panel B: MFPT closed -> open =====
    ax2 = axes[1]

    # ---- Panel B colors (match your Fig.2): APO=black, PIY=red, AND=blue, EST=green, TES=purple ----
    sys_color = {
        "APO": "black",
        "PIY": "red",
        "AND": "blue",
        "EST": "green",
        "TES": "purple",
    }
    bar_colors = [sys_color.get(s.upper(), "gray") for s in systems]
    ax2.bar(x, mfpt_frames, color=bar_colors)

    ax2.set_xticks(x)
    ax2.set_xticklabels(systems)
    ax2.set_ylabel("MFPT (closed → open, frames)")
    ax2.set_title("Gate opening kinetics")

    plt.tight_layout()
    plt.savefig("FigureX_MSM_mouth_cover.png", dpi=300)
    plt.show()

if __name__ == "__main__":
    main()
